directories:
  base_directory: ""
  source_dir: "/"
  destination_base_dir: ""
logs:
  unclassified_log: "unclassified_files.log"
  copied_log: "copied_files.log"
  replaced_log: "replaced_files.log"
  skipped_log: "skipped_files.log"
